# -*- coding: utf-8 -*-
"""app(f).py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwBBoFCIlV-VE9buaTJa88yOApzlhbKn
"""

from flask import Flask, render_template, request
import pickle
# Loading model and cv
cv = pickle.load(open('vectorizer.pkl', 'rb'))  # loading cv
model = pickle.load(open('nb_model.pkl', 'rb'))  # loading model

app = Flask(__name__)  # defining flask name


@app.route('/')  # home route
def home():
    # at home route returning index.html to show
    return render_template('index.html')


@app.route('/predict', methods=['POST'])  # on post request /predict
def predict():
    if request.method == 'POST':
        mail = request.form['text']  # requesting the content of the text field
        data = [mail]  # converting text into a list
        # transforming the list of sentence into vecotor form
        vect = cv.transform(data).toarray()
        pred = model.predict(vect)  # predicting the class(1=spam,0=ham)
        if pred == 0:
            return render_template('index.html', prediction_text='It is a ham text')
        else:
            return render_template('index.html', prediction_text='It is  spam')


if __name__ == '__main__':
    app.run()
